name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish --configuration Release --no-build -p:PublishSingleFile=true -p:SelfContained=false --runtime win-x64
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: launcher
        path: Launcher/bin/Release/net8.0-windows7.0/win-x64/publish/launcher.exe